/**
 * Master list of Tamil Nadu districts and major cities/towns.
 * The application is focused specifically on Tamil Nadu creators.
 * Sorted alphabetically.
 */

export const CITIES = [
  'Ambur',
  'Ariyalur',
  'Attur',
  'Bhavani',
  'Bodinayakkanur',
  'Chengalpattu',
  'Chennai',
  'Chidambaram',
  'Coimbatore',
  'Coonoor',
  'Cuddalore',
  'Dharapuram',
  'Dharmapuri',
  'Dindigul',
  'Erode',
  'Gudiyatham',
  'Hosur',
  'Kallakurichi',
  'Kanchipuram',
  'Kanyakumari',
  'Karaikudi',
  'Karur',
  'Kovilpatti',
  'Krishnagiri',
  'Kumbakonam',
  'Madurai',
  'Manapparai',
  'Mayiladuthurai',
  'Mettupalayam',
  'Mettur',
  'Nagapattinam',
  'Nagercoil',
  'Namakkal',
  'Neyveli',
  'Nilgiris',
  'Ooty',
  'Palani',
  'Panruti',
  'Paramakudi',
  'Pattukkottai',
  'Perambalur',
  'Pollachi',
  'Pudukkottai',
  'Rajapalayam',
  'Ramanathapuram',
  'Ranipet',
  'Salem',
  'Sankarankoil',
  'Sivaganga',
  'Sivakasi',
  'Srivilliputhur',
  'Tenkasi',
  'Thanjavur',
  'Theni',
  'Thoothukudi',
  'Tiruchengode',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupathur',
  'Tiruppur',
  'Tiruvallur',
  'Tiruvannamalai',
  'Tiruvarur',
  'Udumalaipettai',
  'Vaniyambadi',
  'Vellore',
  'Viluppuram',
  'Virudhunagar',
].sort()

export const CITY_OPTIONS = CITIES.map(city => ({
  label: city,
  value: city.toLowerCase()
}))
